#ifndef POLKIT_KDE_1_CONFIG_H
#define POLKIT_KDE_1_CONFIG_H

/* config.h. Generated by cmake from config.h.cmake */

#define POLKIT_KDE_1_VERSION "${PROJECT_VERSION}"

#cmakedefine01 HAVE_SYS_PRCTL_H
#cmakedefine01 HAVE_PR_SET_DUMPABLE

#endif
