[Desktop Entry]
Name=PolicyKit Authentication Agent
Name[ca]=Agent d'autenticació del PolicyKit
Name[de]=PolicyKit-Authentifizierungs-Agent
Name[en_GB]=PolicyKit Authentication Agent
Name[es]=Agente de autenticación de PolicyKit
Name[fi]=PolicyKit-tunnistautumisagentti
Name[nl]=Authenticatieagent van PolicyKit
Name[pl]=Usługa uwierzytelnienia PolicyKit
Name[pt]=Agente de Autenticação do PolicyKit
Name[pt_BR]=Agente de Autenticação do PolicyKit
Name[ru]=Агент аутентификации PolicyKit
Name[sr]=Полисикитов агент за аутентификовање
Name[sr@ijekavian]=Полисикитов агент за аутентификовање
Name[sr@ijekavianlatin]=PolicyKitov agent za autentifikovanje
Name[sr@latin]=PolicyKitov agent za autentifikovanje
Name[uk]=Агент розпізнавання PolicyKit
Name[x-test]=xxPolicyKit Authentication Agentxx
Comment=PolicyKit Authentication Agent
Comment[ca]=Agent d'autenticació del PolicyKit
Comment[de]=PolicyKit-Authentifizierungs-Agent
Comment[en_GB]=PolicyKit Authentication Agent
Comment[es]=Agente de autenticación de PolicyKit
Comment[fi]=PolicyKit-tunnistautumisagentti
Comment[nl]=Authenticatieagent van PolicyKit
Comment[pl]=Usługa uwierzytelnienia PolicyKit
Comment[pt]=Agente de Autenticação do PolicyKit
Comment[pt_BR]=Agente de Autenticação do PolicyKit
Comment[ru]=Агент аутентификации PolicyKit
Comment[sr]=Полисикитов агент за аутентификовање
Comment[sr@ijekavian]=Полисикитов агент за аутентификовање
Comment[sr@ijekavianlatin]=PolicyKitov agent za autentifikovanje
Comment[sr@latin]=PolicyKitov agent za autentifikovanje
Comment[uk]=Агент розпізнавання PolicyKit
Comment[x-test]=xxPolicyKit Authentication Agentxx
Exec=${CMAKE_INSTALL_FULL_LIBEXECDIR}/polkit-kde-authentication-agent-1
Terminal=false
Type=Application
Categories=
OnlyShowIn=KDE;
X-KDE-StartupNotify=false
X-KDE-autostart-phase=0
NoDisplay=true
X-DBUS-StartupType=Unique
